version: '3.8'

services:
  backend:
    build:
      context: ./fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
